### ISSUE TITLE
Approving Enables Entry on All Sites

### ISSUE THREAD

**Issue by masonry47** [engram-design/Workflow#110]
### Description
Hi there, we have come across a different issue.  As mentioned in the other post we are using workflow for managing a localized site.  Many editors only have access to one site (therefore one language). So when an editor creates an entry, they often are creating an entry for just one language. So when the publisher uses workflow to publish, "approve and publish" now globally enables the entry on all sites.  "Approve and Publish"  in older versions of Workflow only enabled the entry in the site the draft was created in.  

It doesn't seem like a bug but more of a change in how it works, but the previous way, in 1.34 and below,  when using this for a multi site setup makes much more sense in a publishing workflow.

### Additional info

- Plugin version:1.4.6
- Craft version:3.4.17

Thanks!

**Comment by engram-design** [comment]
I'm not actually sure if this is a Craft core issue, or a Workflow issue. Case in point, try the following with just Craft:

Create a new entry as an editor. Don't click save or submit via Workflow, just give it a title, and fill in any required fields. This will have automatically created a new draft, and through auto-saving, it'll have saved your content. To test, use the site dropdown to switch between all other sites.

Copy/paste the same URL, but instead when logged in as a publisher. You'll then have the option to Create the entry. Clicking this will enable it for all sites, unless you use the new "Enabled Everywhere" function in the sidebar to control with sites have this as live.

I'll give this some consideration, although I don't believe there was any change in behaviour from 1.3.4 to the latest version with regards to this...

**Comment by masonry47** [comment]
Hey Josh, 

I do think it is the way Craft handles this changed in 3.4.  See here.  

https://github.com/craftcms/cms/issues/2899

So we think, though we are certainly no experts in these sort of things, this:

            $event->sender->enabled = true;
            $event->sender->enabledForSite = true;

in the plugin (service.php ) is what "enables" the entry upon the user clicking "approve and publish". Pre 3.4 this would only only enable for the site that the draft was created for.

For our use case and I am sure others who are using multi site for managing localized websites, it is a pretty big problem, because there are alot of editors creating content for just one site (language). So now when a publisher approves, the entry goes live in all languages until the publisher goes back into then entry and disables for the sites that they do not want it live in.   We are playing with adding  a conditional that says something like
            $siteId = $request->getBodyParam('siteId');
            if ($siteId == '1')  {
           
						$event->sender->enabledForSite = [
  							  1 => true,
   							  2 => false,
   							  3 => false,
   							  4 => false,
   							  5 => false,
   							  6 => false,
			];
}

And doing that for each site there is and that seems to do the trick, though I am sure there is a better way to do it dynamically.  

Thanks so much!

**Comment by masonry47** [comment]
I think the problem is doing it this way, is this only works for new entries.  If an editor submitted a change to a "single" or an already created channel or structure entry, you would want the statuses of each site to remain the same.

**Comment by masonry47** [comment]
Sorry!  One additional thing about your point above.  That is dependent on your sections settings.  So in your example when you click create, all versions are enabled because of your Section settings.

We though have all Section settings to default to disabled.  So in the older version  of Workflow, when a publisher clicks approve and publish, it was Workflow that was changing the status of the entry to enabled...... but enabled for only for the site the draft was created for.

But now, with the same setup where sections settings are all defaulted to disabled, when a publisher clicks approve and publish, the draft becomes enabled on all sites.

So it seems this

 $event->sender->enabledForSite = true;

is handled differently by Craft now. 

Thanks so much and sorry for all of the responses but just trying to explain what is going on as best as I can!

**Comment by engram-design** [comment]
That's correct - I knew what the issue was, but not really a nice way to handle it from a publisher point of view. I might need to introduce a list of checkboxes for the publisher widget to allow you to control this, and which site should be enabled.

I think its a bit presumptuous to always expect that only the current site-edited entry is the one that gets enabled, and no others. It would certainly work in your case, but for others, I'm sure this might be desirable behaviour.

And that's correct on the default status for the section.

It might just be a quick-fix for now, but I'll put something together in the short term. I'm working on a bit of a larger refactor for the next major version, so we might properly address it then.

**Comment by engram-design** [comment]
This should be fixed in [1.4.7](https://github.com/verbb/workflow/releases/tag/1.4.7).

Note that in Craft 3.4+ there's a multi-lightswitch pane for "Enabled for ..." where you can define how this entry acts across your sites. Workflow will honour this, so that if you set it only enabled on one site, it'll copy that.

Otherwise, it will only enable it on the site that you have approved, rather than automatically for all.

**Comment by masonry47** [comment]
Thank you! 

Separately sent you an issue that we are still having.  Thanks!
