### ISSUE TITLE
Entry not locked after editor submits for review

### ISSUE THREAD

**Issue by DrewBold** [engram-design/Workflow#124]
When an Editor submits an entry for review to a publisher the entry does not become locked. The entry and its draft (which was submitted for review) are still editable. If an editor changes data in the submitted draft before the publisher approves the entry the new/modified data is present for the publisher to review.

According to the docs the entry should be locked once the entry has been submitted for review.

Running:
Craft Pro 3.4.28.1

Please advise.

**Comment by engram-design** [comment]
Right, so the docs may need to be amended here to clarify Craft's new(ish) behaviour due to draft changes in 3.2. At least if I'm understanding you correctly.

If an editor decides to create a new draft on an existing entry, it's the draft that is submitted for review. The original entry can continue to be updated by other users. For instance, the editor might submit a draft, but it might take a month for the publisher to review it and publish it. The original entry can continue to be edited in the meantime (and more drafts made).

Before Craft 3.2, the drafts system worked differently, so you were really always dealing with the entry.

So that deals with editing the base entry. I'm not sure if we should be locking the base entry from being saved whilst there is a pending submission on the draft.

However, I see what you mean about being able to edit a draft. The save button is hidden, but the autosave function is kicking in. This _was_ working at some point, but I think this was changed due to a PR to add reviewers. This has been fixed in [1.5.5](https://github.com/verbb/workflow/releases/tag/1.5.5)

**Comment by green17** [comment]
Can a there be a setting to lock the base entry from being saved whilst there is a pending submission on the draft?
We are having problems where users are editing and submitting changes - the entries all have matrix blocks so can not be merged.

**Comment by green17** [comment]
@engram-design I see there is movement in the code on this 'Add lockDraftSubmissions' any ideas no when it would be good to use?

**Comment by engram-design** [comment]
Added `lockDraftSubmissions` in [1.5.7](https://github.com/verbb/workflow/releases/tag/1.5.7)
