### ISSUE TITLE
Timestamps in Workflow date columns

### ISSUE THREAD

**Issue by green17** [engram-design/Workflow#172]
### What are you trying to do?

We are running into an issue when multiple submissions for the same entry are submitted on the same day (note: this also applies to entries that are approved on the same day). The drafts appear in Workflow as expected but any beyond the current day display the day submitted/approved only, we would like to be able to see the time submitted/approved alongside the day.

### What's your proposed solution?

Adding the time alongside the day in the "Date Submitted", "Last Reviewed", "Date Approved" and "Date Rejected" columns would solve this.

**Comment by engram-design** [comment]
I assume this is for Workflow 1 for Craft 3, because there's no longer a "Date Approved" and "Date Rejected" column?

As for showing the time, we're just using the built-in date formatter that shows dates in a "short" format (like entries and other elements). So wouldn't this be an issue for entry drafts that have a Post Date in the future? I assume that's what you mean but "beyond the current day"?
