### ISSUE TITLE
When approved: Show the "submit for review" section only after having saved the entry for the first time. 

### ISSUE THREAD

**Issue by outline4** [engram-design/Workflow#29]
Once the entry is approved, please only show the "submit for review" section after saving for the first time.  
It does not make sense to submit an entry without having made any changes.  
I can see my clients submitting an entry multiple times.

And if we're at it: Please consider moving the "approved"-section ABOVE the submit for review section. 

It's great to have workflow for craft v3!  
Thanks a lot!

**Comment by engram-design** [comment]
That's a tricky one, Workflow doesn't current have any concept of checking whether entry content has changed or not. We also can't rely on the versioning being enabled, as some sections aren't. We'll look at adding this in.

What's the reasoning behind having the approved items above the new submission button? The reason for it being first is so that its not lost vertically on the page if there are multiple submissions (approved or otherwise).

**Comment by engram-design** [comment]
This has been addressed in [1.1.0](https://github.com/verbb/workflow/releases/tag/1.1.0). Now, the "Submit for review" button saves and submits content. There still aren't and specific checks on whether content has changed, but this is similar to how a regular save works - you can save an entry multiple times even if nothing has changed.

However, we have also made this more hidden when a previous submission has been approved, under the assumption that once approved it's less of a primary action to submit it again.
