### ISSUE TITLE
Entry not being enabled when Approved

### ISSUE THREAD

**Issue by ghost** [engram-design/Workflow#37]
### Steps to reproduce

1. Editor saves entry and submits for approval
2. Publisher approves entry
3. Entry shows as being approved but doesn't show as enabled

### Additional info

- Plugin version: 1.0.2
- Craft version: Pro 3.0.28

**Comment by engram-design** [comment]
Workflow won't automatically enable or post entries unless the publisher manually opts to do so. This is basically because Workflow acts as just an approval layer, and doesn't effect the entry itself through content or publishing.

We'll be changing this soon to be more involved in the entry process.

**Comment by ghost** [comment]
Ok thanks for the update - we also noticed that the Workflow Dashboard isn't showing the Approved Date and Rejected Date properly. It just shows empty values:

<img width="273" alt="screen shot 2018-11-15 at 7 37 56 am" src="https://user-images.githubusercontent.com/3730133/48556379-6667dd00-e8a9-11e8-8aed-a1d5f18fd5a9.png">

**Comment by engram-design** [comment]
Fixed in [1.1.0](https://github.com/verbb/workflow/releases/tag/1.1.0)
