### ISSUE TITLE
Not seeing individual publishers

### ISSUE THREAD

**Issue by ghost** [engram-design/Workflow#49]
### Description

I installed the plugin into a fresh Craft 3.1.14 release and activated it. I then added a publisher and editor user group. I then added two publisher users. Now when I uncheck "All" in the "Publishers To Receive Notifications" I don't see those two publishers. 

Or am I missing something? 

### Steps to reproduce

As described above.

### Additional info

- Plugin version: 1.1.1
- Craft version: 3.1.14

**Comment by engram-design** [comment]
Updated in [1.1.2](https://github.com/verbb/workflow/releases/tag/1.1.2) - can you give this a go?

**Comment by ghost** [comment]
It works! Now I see my individual publishers and I select the ones I want to send messages too. 

One question (feature request): How difficult would it be to have a selection in the edit screen, so I can select the publisher myself?

In our company scenario, we have tech writing, marking, etc. and each has its own publishers. To not spam them with too many unrelated messages it would be perfect if an editor could choose one (or more) publisher that is relevant for her/him. 

If that is a feasible feature I can make it a feature request issue. 

Thank you for the great plugin! 🏆

**Comment by engram-design** [comment]
Its certainly on the cards, and the next big feature will be better editor/publisher workflows. There's a variety of different scenarios we want to cater for (as provided by the community feedback). However, I'm not sure if that scenario in particular will make it in (it might!), because it could lead to abuse - say one editor always picks a certain publisher to approve their work, and management don't want that to happen, etc. Of course, its a valid use-case for your company.

Having said that, please add this as a new FR so we can keep track of it!

**Comment by ghost** [comment]
No problem! I can communicate that to my client and we will see what scenarios you'll implement. I'm sure we can find one that suits our needs.
