### ISSUE TITLE
Entries aren't actually "enabled" on approval

### ISSUE THREAD

**Issue by mattrothenberg** [engram-design/Workflow#52]
### Description
Upon approving an entry, the entry reflects being "Enabled" by showing the green toggle button.

However, the article doesn't appear on the site until the article is marked as "Disabled," saved, marked as "Enabled" and saved again. This is confusing.

### Steps to reproduce

1. Approve article
2. Visit front-end
3. See that article doesn't appear
4. Disable the article
5. Save
6. Enable the article
7. See that the article appears

### Additional info

- Plugin version: `1.1.3`
- Craft version: `3.1.15`

**Comment by engram-design** [comment]
Can't actually replicate this at the moment. What's your default status for the section? Is this a mult-site?

**Comment by mattrothenberg** [comment]
Both sections are `enabled` by default. This isn't a multi-site. Are there logs that would be helpful to see? I can replicate across dev, staging, and production.

**Comment by engram-design** [comment]
Hmmm, I'll keep at it then! No logs currently for this side of things, but will likely add those in.

Would you be able to test out my updated change by running `composer require verbb/workflow:dev-craft-3`

**Comment by engram-design** [comment]
Aha, found the issue, its to do with the Post Date, if one isn't specified, it won't get created automatically, hence the entry will be enabled, but 'unpublished' as it doesn't have a post date.

Interestingly, on a multi-site install, an approved entry gets its Post Date generated automatically, which was why I wasn't able to reproduce. Odd behaviour.

Fixed in [1.1.4](https://github.com/verbb/workflow/releases/tag/1.1.4)
