### ISSUE TITLE
[Question] Drafts vs. Versions

### ISSUE THREAD

**Issue by mattrothenberg** [engram-design/Workflow#53]
Howdy!

One of the questions I consistently receive from my end users (both editors and publishers) is the difference between versions and drafts? The cognitive load of choosing the right draft/version is causing some pain for them. For example,

<img width="359" alt="screen shot 2019-03-01 at 3 09 23 pm" src="https://user-images.githubusercontent.com/5148596/53663554-0caad900-3c34-11e9-8300-60b2f6f9685e.png">

Moreover, it's also unclear for the publisher, when looking at the Workflow Overview tab, which article should be approved, e.g.,

<img width="971" alt="screen shot 2019-03-01 at 3 10 14 pm" src="https://user-images.githubusercontent.com/5148596/53663606-2f3cf200-3c34-11e9-9cab-f105c1f68028.png">

Any guidance here? I'm sure part of this stems from the fact that my users are perhaps not using the plugin properly. But the unfortunate side-effect of this is that they don't have confidence that their changes are being approved and subsequently appearing. From an editor
```
Notes: "Trying to submit again with a description. I have submitted twice but when I go back in it looks like I haven't and it doesn't save that I entered information in the description area."
```

Is it safe to turn off versions, so as to at least reduce the cognitive load here?

**Comment by engram-design** [comment]
So I wouldn't encourage disabling versions, because drafts and versions are two different things. These are also both Craft core concepts, not something just for Workflow. I think the core of this question actually speaks to how Craft itself manages this (for instance, editing an entry won't show the latest draft, etc)

A version is essentially a backup of each time you save an entry. Good for looking back it its history. A Draft is an un-published copy of an entry.

In the scenario of Workflow, if an editor is making changes to a published entry, they cannot actually save their changes to it, otherwise they would appear live. As such, they're enforced to create a draft and save their changes to that. Workflow will submit this draft for review - and if notifications are setup - notify the publisher with a direct link to the URL to the Draft. Publishers should review this draft then accept/reject it. If a draft is accepted, its basically deleted and merged into the published entry.

Which brings me to the next point, why are there so many drafts for this entry? This could be that the editors submission has been rejected 5 times and they've started a new draft each time?

**Comment by mattrothenberg** [comment]
Thanks for the clarifications.

As to your question about why there are so many drafts, I can't actually
answer that. All I can tell you is that with the current UI and
notification workflow, my users (again, can't speak for anyone else), are
having an extremely difficult time understanding what's going on.
