### ISSUE TITLE
Rejected Entries Still show when approved

### ISSUE THREAD

**Issue by robnathan** [engram-design/Workflow#64]
### Description
![Workflow Test](https://user-images.githubusercontent.com/50607309/57669312-05914580-763d-11e9-8c56-31fa77618683.png)

When an entry is rejected and is subsequently approved the rejected entry remains in the workflow. The entry appears twice in the workflow as shown in the attached.  The rejected entry in the workflow should be removed when it is approved.

### Steps to reproduce

1. Create and Entry
2.Reject an entry
3. Approve an Entry

### Additional info

- Plugin version: Workflow 1.1.9
- Craft version: Craft Pro 3.1.25

**Comment by engram-design** [comment]
This is semi-expected behaviour. Each time a submission is accepted or rejected, it completes the lifecyle of that specific submission. You can submit another one (ideally, with changes made that caused it to be rejected), but this should be filed as a new submission.

I'll look at adding a better way to show this, as you mention, its not ideal at the moment.

**Comment by engram-design** [comment]
This should be greatly improved in [2.0.0](https://github.com/verbb/workflow/releases/tag/2.0.0) thanks to better handling of submissions and reviews. Refer to [blog post](https://verbb.io/blog/workflow-2) and [upgrade docs](https://verbb.io/craft-plugins/workflow/docs/get-started/upgrading-from-v1).
