### ISSUE TITLE
Directly submitting for approval: Entry is missing from list

### ISSUE THREAD

**Issue by d--j** [engram-design/Workflow#94]
### Description

If an editor creates a new entry and directly submits this entry for review – without saving the entry first. The entry is missing from the list of entries.

Workflow likely needs to check if this is a "fresh" draft ([`propagateAll` is 1](https://github.com/craftcms/cms/blob/8f19a7150bc8e1c39e3a4143bafba1405c4719f5/src/templates/_layouts/element.html#L190-L192)) and save the draft with `propagateAll` set (see https://github.com/craftcms/cms/blob/8f19a7150bc8e1c39e3a4143bafba1405c4719f5/src/controllers/EntryRevisionsController.php#L219-L221)

Maybe related to #91

### Steps to reproduce

1. Editor creates new entry (clicks on "New entry" button on the Entries pages)
2. Editor is in the "Create a new entry" page (url `admin/entries/<handle>/<id>?draftId=<draftId>&fresh=1`)
3. Editor fills out all required fields and directly clicks on "Save draft and submit for review" – without clicking on "Save" or "Save and continue editing"
4. The draft was saved and it is awaiting approval.
5. Editor goes to entries overview – the entry/draft that was just saved is not in the overview

![CaseOfTheMissingEntry](https://user-images.githubusercontent.com/100674/68076267-bdb0d700-fdb2-11e9-8681-48df89deed28.gif)

### Additional info

- Plugin version: 1.2.3
- Craft version: Craft Pro 3.3.14

**Comment by engram-design** [comment]
Its a little more complicated than that - because we actually need to publish the draft. Its a little awkward, because technically its working as expected - when you submit a brand new entry for review, its still a draft, and Workflow won't change that. Whenever you're submitting something for approval with Workflow, it should be a draft, not an entry. That's what happens when you hit "Save" on a draft, it publishes those draft changes to update the entry itself. 

But, I can certainly see downsides to leaving the behaviour as-is. The behaviour doesn't really act like the native Save button, which it probably should. Publishing the draft takes place when the publisher user approves the entry. But we can add this step a little earlier.

Changed in [1.3.0](https://github.com/verbb/workflow/releases/tag/1.3.0)
